apiVersion: v1
kind: Service
metadata:
  name: post-management-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: post-management-service
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-management-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: post-management-service
  template:
    metadata:
      labels:
        app: post-management-service
    spec:
      containers:
        - name: post-management-service
          image: laerkeimeland/post-management-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
