apiVersion: v1
kind: Service
metadata:
  name: timeline-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: timeline-service
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeline-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: timeline-service
  template:
    metadata:
      labels:
        app: timeline-service
    spec:
      containers:
        - name: timeline-service
          image: laerkeimeland/timeline-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
