name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    # Restore dependencies for each service
    - name: Restore dependencies for Authentication Service
      run: dotnet restore "AuthenticationService/AuthenticationService.csproj"

    - name: Restore dependencies for Notification Service
      run: dotnet restore "NotificationService/NotificationService.csproj"

    - name: Restore dependencies for Post Management Service
      run: dotnet restore "PostManagementService/PostManagementService.csproj"

    - name: Restore dependencies for Timeline Service
      run: dotnet restore "TimelineService/TimelineService.csproj"

    - name: Restore dependencies for User Management Service
      run: dotnet restore "UserManagementService/UserManagementService.csproj"

    # Build each service
    - name: Build Authentication Service
      run: dotnet build "AuthenticationService/AuthenticationService.csproj" --no-restore

    - name: Build Notification Service
      run: dotnet build "NotificationService/NotificationService.csproj" --no-restore

    - name: Build Post Management Service
      run: dotnet build "PostManagementService/PostManagementService.csproj" --no-restore

    - name: Build Timeline Service
      run: dotnet build "TimelineService/TimelineService.csproj" --no-restore

    - name: Build User Management Service
      run: dotnet build "UserManagementService/UserManagementService.csproj" --no-restore

  dockerize:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker image for Authentication Service
    - name: Build Docker image for Authentication Service
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/authentication-service:latest -f "AuthenticationService/Dockerfile" .

    # Build Docker image for Notification Service
    - name: Build Docker image for Notification Service
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/notification-service:latest -f "NotificationService/Dockerfile" .

    # Build Docker image for Post Management Service
    - name: Build Docker image for Post Management Service
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/post-management-service:latest -f "PostManagementService/Dockerfile" .

    # Build Docker image for Timeline Service
    - name: Build Docker image for Timeline Service
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/timeline-service:latest -f "TimelineService/Dockerfile" .

    # Build Docker image for User Management Service
    - name: Build Docker image for User Management Service
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/user-management-service:latest -f "UserManagementService/Dockerfile" .

    # Push Docker images for all services
    - name: Push Docker image for Authentication Service
      run: docker push ${{ secrets.DOCKER_USERNAME }}/authentication-service:latest

    - name: Push Docker image for Notification Service
      run: docker push ${{ secrets.DOCKER_USERNAME }}/notification-service:latest

    - name: Push Docker image for Post Management Service
      run: docker push ${{ secrets.DOCKER_USERNAME }}/post-management-service:latest

    - name: Push Docker image for Timeline Service
      run: docker push ${{ secrets.DOCKER_USERNAME }}/timeline-service:latest

    - name: Push Docker image for User Management Service
      run: docker push ${{ secrets.DOCKER_USERNAME }}/user-management-service:latest
